// flow-typed signature: 287d59e8b265bd5d23b98d75fed32e4a
// flow-typed version: <<STUB>>/loader-utils_v^0.2.3/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'loader-utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'loader-utils' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'loader-utils/index' {
  declare module.exports: $Exports<'loader-utils'>;
}
declare module 'loader-utils/index.js' {
  declare module.exports: $Exports<'loader-utils'>;
}
